spring.application.name=Backend
server.port=8080

# MongoDB
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://mongo:27017/copdb}

# Disable SQL auto config if present
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

logging.level.org.springframework.data.mongodb=INFO
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
